#!/bin/bash

file1=$(wc -l < LogData_User.node4F)
file2=$(wc -l < LogData_User.node4B)
file3=$(wc -l < LogData_User.node4C)
file4=$(wc -l < LogData_User.node4D)
file5=$(wc -l < LogData_User.node4E)
file6=$(wc -l < LogData_User.node50)
file7=$(wc -l < LogData_User.node51)
file8=$(wc -l < LogData_User.node52)

val=8

split -l $(($(($file1+$val-1))/$val)) LogData_User.node4F -d splits/LogData_User.node4F_
split -l $(($(($file2+$val-1))/$val)) LogData_User.node4B -d splits/LogData_User.node4B_
split -l $(($(($file3+$val-1))/$val)) LogData_User.node4C -d splits/LogData_User.node4C_
split -l $(($(($file4+$val-1))/$val)) LogData_User.node4D -d splits/LogData_User.node4D_
split -l $(($(($file5+$val-1))/$val)) LogData_User.node4E -d splits/LogData_User.node4E_
split -l $(($(($file6+$val-1))/$val)) LogData_User.node50 -d splits/LogData_User.node50_
split -l $(($(($file7+$val-1))/$val)) LogData_User.node51 -d splits/LogData_User.node51_
split -l $(($(($file8+$val-1))/$val)) LogData_User.node52 -d splits/LogData_User.node52_
