#! /bin/bash
DUMP_FILES_PATH=~/deleteme/
RDD_TOOL_PATH=gInstall/rrdtool/bin/rrdtool
OUTPUT_PATH=~/output_files/
for file in `ls -1 $DUMP_FILES_PATH*.rdd`
do
base_file=`echo $(basename "$file") | cut -f1 -d'.'`
base_file+=".xml"
echo "$RDD_TOOL_PATH dump $file > $OUTPUT_PATH$base_file"
done
